### ISSUE TITLE
Is this client suitable for desktop applications?

### ISSUE THREAD

**Issue by davidlivingrooms** [launchdarkly/node-client#126]
Hello, 

Is launchdarkly meant to be used for desktop applications? And If so, would this client be safe to use in electron?

I can't find anything on the main website that mentions desktop apps. I also saw a comment like this for the dotNet client https://github.com/launchdarkly/dotnet-client/issues/37#issuecomment-278108490. I just want to make sure i'm not misusing launchdarkly and introducing a security issue. Thanks!

**Comment by eli-darkly** [comment]
Hi - thanks for asking. The answer currently is no: this Node SDK is meant only for server-side use. However, as Electron is gaining popularity, we've had more and more inquiries about this use case and we are currently working on an SDK specifically for Electron.

Here's some more detail about the problem. Since SDKs like the Node one are meant for an environment like a web app, where many requests are being handled for many users and flags need to be evaluated quickly, they don't ask LaunchDarkly to give them flag values for specific users. Instead, they download the entire definition of each flag—targets, rules, etc.—and the SDKs know how to interpret those flag properties to get the right value for each user. There potential security problem with this in a desktop or mobile environment is that the flag details could contain sensitive details like the emails of other users, or internal business logic that you don't want to expose. Now, it is an SSL connection, so theoretically these details are still being sent securely. *However*, the credential used by the SDK has to be somewhere in your code or in a configuration file, and anyone who gets that credential is able to query LaunchDarkly and see all the details of your flag definitions... so it's best to avoid sending that out into the world.

The mobile SDKs, and the [JavaScript browser SDK](https://github.com/launchdarkly/js-client), use a different design: they query a different LaunchDarkly endpoint to get just the flag _values_ for one specific user—using a different credential which cannot do anything but that. This addresses the security issue, and it also uses much less bandwidth. So for desktop use this is the more desirable approach.

The browser SDK is very close to what you would want to use in Electron, and in fact it can be used in the browser (renderer) part of an Electron app, but it won't work quite right in the main process because it does assume it's running in a browser. So we're currently working on an alternate version of it that will run correctly in the main process.

**Comment by davidlivingrooms** [comment]
Okay thank you for your answer. Closing this issue.

**Comment by eli-darkly** [comment]
@davidlivingrooms If you'd like to be notified when we have a beta of the Electron SDK available, drop me an email at eli@launchdarkly.com.
